version: '3.3'
services:

  traefik:
    image: "traefik:v2.8.4"
    container_name: traefik
    hostname: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.le.acme.email=aitbenhaanass@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users="
    restart: unless-stopped


  backend:
    image: backend:latest
    command: bash run.sh
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.backend.rule=Host(`api.enginchantier.ma`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=5656"
    environment:
      - APP_NAME=engin.ma
      - APP_HOST=backend
      - APP_PORT=5656
      - APP_DEBUG=false
      - IS_PRODUCTION=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=enginchantier
      - DB_USER=enginchantier
      - DB_PASSWORD=jG806sNiP756
      - LOGGING_LEVEL=INFO
      - LOGGING_FILENAME=_
      - JWT_SECRET=TRABORODJWTSECRET
      - JWT_EXPIRATION=120 
      - JWT_REFRESH_EXPIRATION=2592000
      - ENABLE_SWAGGER_UI=True #False to disable Swagger UI

    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=enginchantier
      - POSTGRES_PASSWORD=jG806sNiP756
      - POSTGRES_DB=enginchantier
    ports:
      - '5432:5432'
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  letsencrypt:
  mydata:
  vault-data:

networks:
  default:
    external: true
    name: proxy