version: '3.3'
services:
  backend-test:
    image: backend:latest
    command: bash run.sh
    build: .
    container_name: backend-test
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.backend-test.rule=Host(`sandbox.enginchantier.ma`)"
      - "traefik.http.routers.backend-test.entrypoints=websecure"
      - "traefik.http.routers.backend-test.tls=true"
      - "traefik.http.routers.backend-test.tls.certresolver=le"
      - "traefik.http.routers.backend-test.service=backend-test"
      - "traefik.http.services.backend-test.loadbalancer.server.port=5656"
    environment:
      - APP_NAME=engin.ma
      - APP_HOST=backend-test
      - APP_PORT=5656
      - APP_DEBUG=true
      - IS_PRODUCTION=false
      - DB_HOST=db-test
      - DB_PORT=5432
      - DB_NAME=enginchantier_test
      - DB_USER=enginchantier_test
      - DB_PASSWORD=jG806sNiP756
      - LOGGING_LEVEL=INFO
      - LOGGING_FILENAME=_
      - JWT_SECRET=TRABORODJWTSECRETTEST
      - JWT_EXPIRATION=120
      - JWT_REFRESH_EXPIRATION=2592000
      - ENABLE_SWAGGER_UI=True
      - EMAIL_NOTIFICATION_SENDER=naderennawader@gmail.com
      - EMAIL_NOTIFICATION_PASSWORD=zlhm dutz lomr tmby
    volumes:
      - ./uploads-test:/Enginchantier/uploads
    depends_on:
      - db-test
    networks:
      - proxy

  db-test:
    image: postgres:14.1-alpine
    container_name: db-test
    restart: always
    environment:
      - POSTGRES_USER=enginchantier_test
      - POSTGRES_PASSWORD=jG806sNiP756
      - POSTGRES_DB=enginchantier_test
    ports:
      - '5433:5432'
    volumes:
      - mydata-test:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  mydata-test:

networks:
  proxy:
    external: true
