''' Input DTO for creating a booking.'''
from flask_restx import fields, Namespace
from dto.input.validator import required, valid_string, valid_datetime
from models.booking import Booking
from models.user import User
from models.equipment import Equipment

class CreateBookingForm:
    ''' Input form for creating a booking. '''

    def __init__(self, json_input):
        self.client_id = required("client_id", json_input)
        self.client_id = valid_string(self.client_id)

        self.equipment_id = required("equipment_id", json_input)
        self.equipment_id = valid_string(self.equipment_id)

        self.pilot_id = required("pilot_id", json_input)  # Optional: can validate if nullable
        self.pilot_id = valid_string(self.pilot_id) if self.pilot_id else None

        self.start_date = required("start_date", json_input)
        self.start_date = valid_datetime(self.start_date, format="%Y-%m-%d")

        self.end_date = required("end_date", json_input)
        self.end_date = valid_datetime(self.end_date, format="%Y-%m-%d")

        # Booking is always created with "PENDING" status by default
        self.status = "PENDING"

    @staticmethod
    def api_model(namespace: Namespace):
        ''' Returns the API model for booking creation. '''
        return namespace.model("CreateBookingForm", {
            "client_id": fields.String(required=True, description="ID of the client"),
            "equipment_id": fields.String(required=True, description="ID of the equipment"),
            "pilot_id": fields.String(required=False, description="ID of the pilot (if any)"),
            "start_date": fields.String(required=True, description="Booking start date (YYYY-MM-DD)"),
            "end_date": fields.String(required=True, description="Booking end date (YYYY-MM-DD)"),
        })
    def to_domain(self):
        """Converts the form data to a Booking domain model."""
        return Booking(
            id=None,  # ID is generated by the database
            client=User(id=self.client_id) if self.client_id else None,
            equipment=Equipment(id=self.equipment_id) if self.equipment_id else None,
            pilot=User(id=self.pilot_id) if self.pilot_id else None,
            start_date=self.start_date,
            end_date=self.end_date,
            status=self.status
        )
