''' CreateImageForm DTO '''
from flask_restx import Namespace, fields
from models.equipment_image import EquipmentImage
from dto.input.validator import required, valid_string

class CreateImageForm:
    ''' Form to create a equipment image '''
    def __init__(self , json_image=None):
        if json_image is not None:
            self.image_url = required("image_url", json_image)
            self.image_url = valid_string(self.image_url)

            self.equipment_id = required("equipment_id", json_image)
            self.equipment_id = valid_string(self.equipment_id)

    def to_domain(self):
        ''' Converts the form to a domain object. '''
        return EquipmentImage(
            id=None,  # ID will be generated by the database
            equipment_id=self.equipment_id,
            url=self.image_url
        )
    
    @staticmethod
    def api_model(namespace: Namespace):
        ''' Returns the API model for the form. '''
        return namespace.model('CreateImageForm', {
            'image_url': fields.String(required=True, description='URL of the image'),
            'equipment_id': fields.String(required=True, description='ID of the equipment')
        })